### PR TITLE
bugfix on weights

### PR DESCRIPTION
**Pull request by PabloCorcho**
There was a bug on the computation of weights in `ParticleGridCEM`

### CODE REVIEW

**Review by paranoya — COMMENTED** [review]
@PabloCorcho , check whether this is ready to go

**Comment by PabloCorcho** [comment]
I fixed a potential issue at `masses = np.ones_like(ages)`, since this way the masses would inherit the age unit.

**Review by paranoya — COMMENTED** [review]
I trust you, but I didn't spot the bug ;^D

**Comment by PabloCorcho** [comment]
When you implemented get_weights did you intended it to be a staticmethod? Otherwise you forgot to include the `self` argument in the method

**Pull request merged**
